# Generated by Django 4.1.7 on 2023-03-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermakepoints',
            old_name='screen_shot',
            new_name='screen_short',
        ),
    ]
