# Generated by Django 4.1.7 on 2023-03-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_screen_shot_usermakepoints_screen_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totalpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.usermakepoints')),
            ],
        ),
    ]
