# Generated by Django 4.1.7 on 2023-03-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_socialapp_app_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermakepoints',
            old_name='screen_short',
            new_name='screen_shot',
        ),
    ]
